function estaFuncionDePruebasLanzaUnaExcepcion() {
    throw new Error("Esto es una prueba de lanzar una excepcion.");
}

export { estaFuncionDePruebasLanzaUnaExcepcion };
